export const DEPARTMENTS = [
  'PG',
  'M.Com',
  'M.A English',
  'UG',
  'B.Com',
  'B.Com CA',
  'BBA',
  'B.Sc Computer Science',
  'BCA',
  'B.Sc Chemistry',
  'B.Sc Physics',
  'B.Sc Mathematics',
  'B.A English',
  'B.A Tamil',
  'B.A History',
];
